# Generated by Django 4.0.3 on 2022-04-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=1000)),
                ('code_in_question', models.CharField(max_length=800)),
                ('choice_a', models.CharField(max_length=1000)),
                ('choice_b', models.CharField(max_length=1000)),
                ('choice_c', models.CharField(max_length=1000)),
                ('choice_d', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
