# Generated by Django 4.0.3 on 2022-04-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizbrain', '0002_alter_quiz_code_in_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='choice_a',
            new_name='choice_list',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice_d',
        ),
    ]
