# Generated by Django 4.0.3 on 2022-04-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbrain', '0003_rename_choice_a_quiz_choice_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='choice_list',
            new_name='choice_1',
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice_2',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice_3',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
